# Generated by Django 5.2 on 2025-04-05 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_recipe_imag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='imag',
            new_name='image',
        ),
    ]
